/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : bigint,
  'service' : string,
  'status' : LeadStatus,
  'name' : string,
  'createdAt' : bigint,
  'message' : string,
  'phone' : string,
}
export type LeadStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'inProgress' : null };
export type Role = { 'client' : null } |
  { 'admin' : null } |
  { 'staff' : null };
export interface User {
  'id' : bigint,
  'username' : string,
  'role' : Role,
  'isActive' : boolean,
  'passwordHash' : string,
}
export interface UserProfile {
  'username' : string,
  'userId' : bigint,
  'name' : string,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUser' : ActorMethod<[string, string, Role], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : bigint, 'role' : Role } } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[string, string, string, string], bigint>,
  'toggleUserActive' : ActorMethod<[bigint], boolean>,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];