/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'staff' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'createdAt' : IDL.Int,
  'authorName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
});
export const ServiceRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : ServiceRequestStatus,
  'serviceType' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'clientUserId' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : LeadStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createServiceRequest' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteServiceRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientServiceRequests' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initAdmin' : IDL.Func([], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listAllServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : Role }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'toggleUserActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
  'updateServiceRequestStatus' : IDL.Func(
      [IDL.Nat, ServiceRequestStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'staff' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'createdAt' : IDL.Int,
    'authorName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
  });
  const ServiceRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : ServiceRequestStatus,
    'serviceType' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'clientUserId' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : LeadStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createServiceRequest' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteServiceRequest' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientServiceRequests' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initAdmin' : IDL.Func([], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listAllServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : Role }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'toggleUserActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
    'updateServiceRequestStatus' : IDL.Func(
        [IDL.Nat, ServiceRequestStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };