/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'createdAt' : bigint,
  'authorName' : string,
  'updatedAt' : bigint,
  'excerpt' : string,
}
export interface Booking {
  'id' : bigint,
  'service' : string,
  'status' : BookingStatus,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
  'phone' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'confirmed' : null };
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'serviceType' : string,
  'createdAt' : bigint,
  'dueDate' : string,
  'currency' : string,
  'notes' : string,
  'clientUserId' : bigint,
  'amount' : bigint,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface Lead {
  'id' : bigint,
  'service' : string,
  'status' : LeadStatus,
  'name' : string,
  'createdAt' : bigint,
  'message' : string,
  'phone' : string,
}
export type LeadStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'inProgress' : null };
export type Role = { 'client' : null } |
  { 'admin' : null } |
  { 'staff' : null };
export interface ServiceRequest {
  'id' : bigint,
  'status' : ServiceRequestStatus,
  'serviceType' : string,
  'staffNote' : string,
  'clientName' : string,
  'assignedStaffId' : [] | [bigint],
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'clientUserId' : bigint,
}
export type ServiceRequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface User {
  'id' : bigint,
  'username' : string,
  'role' : Role,
  'isActive' : boolean,
  'passwordHash' : string,
}
export interface UserProfile {
  'username' : string,
  'userId' : bigint,
  'name' : string,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStaffNote' : ActorMethod<[bigint, string], boolean>,
  'adminResetPassword' : ActorMethod<[bigint, string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignStaffToRequest' : ActorMethod<[bigint, bigint], boolean>,
  'cancelServiceRequest' : ActorMethod<[bigint], boolean>,
  'changePassword' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createBlogPost' : ActorMethod<[string, string, string, string], bigint>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'createInvoice' : ActorMethod<
    [bigint, string, bigint, string, string, string],
    bigint
  >,
  'createServiceRequest' : ActorMethod<
    [bigint, string, string, string],
    bigint
  >,
  'createUser' : ActorMethod<[string, string, Role], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteBooking' : ActorMethod<[bigint], boolean>,
  'deleteServiceRequest' : ActorMethod<[bigint], boolean>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientServiceRequests' : ActorMethod<[bigint], Array<ServiceRequest>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getRevenueStats' : ActorMethod<
    [],
    {
      'resolvedLeads' : bigint,
      'completedRequests' : bigint,
      'totalLeads' : bigint,
      'pendingRequests' : bigint,
      'newLeads' : bigint,
      'inProgressRequests' : bigint,
      'totalRequests' : bigint,
    }
  >,
  'getStaffAssignedRequests' : ActorMethod<[bigint], Array<ServiceRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'listAllServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listClientInvoices' : ActorMethod<[bigint], Array<Invoice>>,
  'listUsers' : ActorMethod<[], Array<User>>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : bigint, 'role' : Role } } |
      { 'err' : string }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitLead' : ActorMethod<[string, string, string, string], bigint>,
  'toggleUserActive' : ActorMethod<[bigint], boolean>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, boolean],
    boolean
  >,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], boolean>,
  'updateInvoiceStatus' : ActorMethod<[bigint, InvoiceStatus], boolean>,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], boolean>,
  'updateServiceRequestStatus' : ActorMethod<
    [bigint, ServiceRequestStatus],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];