/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : LeadStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'role' : Role,
  'isActive' : IDL.Bool,
  'passwordHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : Role }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'toggleUserActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : LeadStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'role' : Role,
    'isActive' : IDL.Bool,
    'passwordHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : Role }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'toggleUserActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };